### ISSUE TITLE
[US-09] City modification

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#19]
This issue is created to address the user story "City Modification" The user story is described as follows:

_As an administrator, I need the ability to modify city data, such as the name, country, continent, and description. Additionally, I want the capability to add new images to each city's profile._

### Tasks

- [ ] Create protected API endpoint for administrators
- [ ] Securely store updated user profile information in the system database
- [ ] Handle errors during the profile modification process and notify the user in case of issues
