### ISSUE TITLE
Dockerization of Project

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#2]
Building upon the recently established project setup and directory structure, the goal of this issue is to Dockerize the project for enhanced development and deployment consistency.

### Tasks

- [x] Create the neccesary **_Dockerfiles_**.
- [x] Develop a **_docker-compose.yml_** file to orchestrate multi-container deployments.
- [x] Handle environment-specific configurations using an **_.env_** file
- [x] Update the project's **_README.md_** with instructions on how to use Docker.

### Related issues
- #1
