### ISSUE TITLE
[US-17] City comments visualization

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#22]
This issue address the user story "City comments visualization". The user story is described as follows:

_As a user, I want to be able to inspect comments left by other users on a city. I want to view the comments and the associated ratings for each city._

### Tasks

- [ ]  Develop an protected API endpoint to get all city comments.
- [ ] Implement comment visualization view in the user interface.

### Acceptance criteria

- [ ] Users should be able to access the comment visualization view directly from the city's page.
- [ ] Only authenticated users should have access to the comment visualization feature.
