### ISSUE TITLE
[US-12] City tag assignation

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#23]
This issue issue is created to address the user story "City tag assignation". The user story is described as follows:

_As a user, I want the ability to assign descriptive tags to a city. This will enable me to provide a more detailed description of my experience in the city and improve the system's ability to recommend similar cities._

### Tasks

- [ ] Create an protected API endpoint to get all city comments.
- [ ] Set up a tag association form in the user interface.
- [ ] Handle errors during the comment creation process.

### Acceptance criteria

- [ ] Users should be able to access the city tag association form from the city's page.
- [ ] Upon submitting the form, the associations should be stored in the database.
- [ ] Only authenticated users should have access to the city tag association feature.
