### ISSUE TITLE
[US-13] City search by text description

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#24]
This issue is created to address the user story "City search by text description". The user story is described as follows:

_As a user, I want the ability to search cities by a text description and obtain appropriate results. This will achieve a better experience while looking for my next destination._

### Tasks

- [ ] Implement a Text-Based Search Engine
- [ ] Implement an Endpoint to Query the Descriptions
- [ ] Design and develop an intuitive user interface where users can enter their city descriptions
