### ISSUE TITLE
[US-14] City Similarity Recommendations

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#25]
This issue is created to address the user story "City Similarity Recommendations". The user story is described as follows:

_As a user, I want to recieve recommendations for cities that are similar to the city im currently viewing. These recommendations should be based on the city tags users assign to the cities when they place a comment. I would like these suggestions to be easily accessible and accompanied by key information about each recommended city._

### Tasks

- [ ] Research and Select Comparison Criteria
- [ ] Recommendation Engine Implementation
- [ ] User Interface Design and Implementation
