### ISSUE TITLE
[US-15] City recommendations based on user profile

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#26]
This issue is created to address the user story "City recommendations based on user profile". The user story is described as follows:

_As a user, I want to recieve recommendations for cities that match my profile. These recommendations should be based on the tags I've assigned to my profile and the characteristics of the evaluated  cities, so that I can discover cities that align my personal preference and lifestyle_

### Tasks

- [ ] Research and Select Comparison Criteria
- [ ] Recommendation System Implementation
- [ ] User Interface Design and Implementation
