### ISSUE TITLE
Database Implementation

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#5]
This issue is created to track the implementation of the database as part of milestone of the same title: Database Implementation.

### Tasks:

- [x] Evaluate and select the most suitable database for the project's needs (docs).
- [x] Establish appropriate connection configuration between the application and the database.
- [x] Design and define database schemas, including tables, relationships, and fields.
