### ISSUE TITLE
[US-01] User Registration

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#8]
This issue is created to address the user story "Register Users". The user story is described as follows:

_As a prospective user, I aim to have a seamless experience registering on the platform. I want the registration process to be user-friendly, allowing me to input my personal information effortlessly. The system should validate the provided data, ensuring its accuracy and completeness_

### Tasks

- [x] Create API endpoint for user registration
- [x] Validate the information provided during the registration process to ensure data integrity and authenticity.
- [x] Securely store user information in the system database
- [x] Handle errors during the registration process and notifying the user in case of problems
- [x] Create User Registration Web Interface

### Acceptance Criteria

- [x] Registration must include all the necesary data and be validated correctly
- [x] User registration information must be correctly stored in the database
- [x] Errors must be handled, and an appropriate error response must be returned
