### ISSUE TITLE
[US-02] User Tag Assignment

### ISSUE THREAD

**Issue by fjromeero** [fjromeero/NomadCities#9]
This issue issue is created to address the user story "User tag assigment". The user story is described as follows:

_ As a prospective user, I want to have the ability to assign tags to my profile. This will allow me to organize and personalize my experience on the platform_

### Tasks

- [ ] Create API endpoint for user tag assigment
- [ ] Securely store tag assignment in the system database
- [ ] Handle errors during the assignment process
- [ ] Create a web interface for User Tag Assignment
